### ISSUE TITLE
PCF - application metrics 

### ISSUE THREAD

**Issue by RobiD** [cloudfoundry-community/firehose_exporter#1]
We managed to get this running on a Docker instance, which then connects to Doppler and receives the metrics. Good job for implementing the exporter! :-)

However, we are not interested in all the metrics, but only metrics for specific application. Would it be possible to expose an endpoint only for a specific PCF app, and how could we do it?

**Comment by mjseid** [comment]
I have a slightly similar request.  In my case I only want application container metrics in prometheus, since I'm using other tools (https://github.com/cloudfoundry-incubator/datadog-firehose-nozzle) to capture CF platform specific metrics.  I forked your current code and simply don't initialize any of the other MetricsCollectors besides container but if others are interested in the same thing, it might be helpful to put a flag in for exporting only container metrics.

@RobiD if you had that functionality, would it be good enough to then sort for the app inside of prometheus?  Something like firehose_exporter_containermetric_cpu_percentage{application_id="xxxxxxx"}

**Comment by frodenas** [comment]
@RobiD I've been thinking about this for a while. My reasoning so far is that this exporter should be used to get `platform metrics` and not used to get particular `application metrics`. Connecting to the firehose to get container metrics requires a client with enough permissions. I believe it's better to have a different exporter that, using the app developer auth token, can fetch only the container metrics for their applications ([similar to this approach](https://github.com/cloudfoundry/noaa/blob/master/samples/container_metrics/consumer/main.go)).

On the other hand, having a different exporter might be a non-sense, and we already have filters for `events` and `deployments`, so why not add a new filter?

Thoughts?

I'm going to leave this issue open until we find the right approach. In the meantime, I suggest using @mjseid solution. You can now filter by `ContainerMetric` events, and then query prometheus using the `application_id` filter.

BTW, I'd like to add more labels to `ContainerMetrics`, like the `org`, `space` and `app_name`. Is this something you will find useful?

@mjseid I implemented that flag 2 days ago :) 

```
doppler.events ($FIREHOSE_EXPORTER_DOPPLER_EVENTS)
Comma separated events to filter (`ContainerMetric`, `CounterEvent`, `ValueMetric`)
```

And thanks for finding a solution to @RobiD question!

**Comment by mjseid** [comment]
Oh, I forked sometime last week so I didn't realize you added that flag.  Awesome!

The only other thing I do in my fork is poll a custom service we already have running to get some info so I can add the org,space,app_name labels (having just app_id is not very user friendly).  So yes, I would find that very useful if you added that feature as well :-)

**Comment by RobiD** [comment]
@mjseid and @frodenas thanks for the advice! We have solved this problem on Grafana level, by filtering the metrics out by application_id.

**Comment by frodenas** [comment]
Thanks @mjseid and @RobiD. I'm going to close this issue for now and I'll open a new one requesting to have labels for org, space, and app names at the `ContainerMetrics`.
