### ISSUE TITLE
HttpStartStop filter

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-community/firehose_exporter#10]
The [current supported](https://github.com/cloudfoundry-community/firehose_exporter/blob/master/filters/event_filter_test.go#L24-L44) filters do not yet include HttpStartStop. While I understand from https://github.com/cloudfoundry-community/firehose_exporter/issues/1#issuecomment-255870720 that this exporter is designed for a platform operator to collect platform metrics, I believe exporting a subset of the HttpStartStop would be useful:

An operator can currently use the [cf apps metrics](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/src/cloudfoundry_dashboards/cf_apps_metrics.json) dashboard to check the metrics for a given app, e.g. to identify a "greedy app" that is using lots of fair cpu cycles.

It seems useful to enrich such per app dashboard for a cf operator platform with data from the [HttpStartStop](https://github.com/cloudfoundry/dropsonde-protocol/blob/master/events/README.md#events.HttpStartStop) event:
- routing traffic request rate (nb requests per second) 
- routing traffic latency (stopTimestamp - startTimestamp )
- routing traffic bandwidth (only contentLength available, i.e. size of response, request size not yet available)
- routing traffic distribution on app instances (instanceIndex)
- routing traffic error rate (http statusCode)

The associated use-cases for a CF platform operators would be:
- drilldown on some aggregated [routing metrics](http://docs.cloudfoundry.org/loggregator/all_metrics.html#routing) when the routing layer is overloaded:
   > latency 	Time in milliseconds that the Gorouter took to handle requests to its application endpoints. Emitted per router request.
   > routed_app_requests 	The collector sums up requests for all dea-{index} components for its output metrics. Emitted every 5 seconds.
- correlate diego cpu overprovisionning with application reported impacts, such as slow app performance (typically measure with latency of responses on incoming http requests)
- troubleshoot unbalanced gorouter load balancing among app instances of a given app (when routing tables are stale/not fresh)
- correlate application-reported errors (502 bad gateway status) with diego health management metrics/events

A last use-case I'm studying, is whether exporting HttpStartStop data could be used within the [cloudfoundry-community/autosleep](https://github.com/cloudfoundry-community/autosleep) service to help get a more reliable measure of the date of last http traffic for a given application. This date is used an indicator of an application inactivity and triggers an automatic stopping the enrolled applications. Autosleep is currently using the [recentlogs](https://github.com/cloudfoundry/loggregator/blob/develop/src%2Ftrafficcontroller%2FREADME.md#endpoints) doppler endpoint. However this has some precision/performance limitations (https://github.com/cloudfoundry-community/autosleep/issues/187 ) that prometheus could help solve (https://github.com/cloudfoundry-community/autosleep/issues/264#issuecomment-262497809 ) if part of the HttpStartStop events would be exported.

**Comment by frodenas** [comment]
@gberche-orange The idea behind this exporter was to behave as a simple proxy to convert Firehose metrics to a Prometheus metrics format. Dealing with `HttpStartStop` events presents some challenges:

* Prometheus is a monitoring and alerting system.  Although it implements a dimensional data model to store its metrics, it's **not** a time-series database (like InfluxDB or OpenTSDB). This means I cannot simply export the `HttpStartStop` events as is because this is not how Prometheus works. Prometheus uses a pull model (periodic scrapes), you cannot repeat the same metric with the same labels and different values on a single scrape, and it does not allow sending metrics timestamps.

* When exporting `ContainerMetrics`, `CounterEvents` and `ValueMetrics` I took the approach to reporting the last metric gathered from the Firehose, mainly because those metrics are already aggregated/summarized by the Firehose. But this cannot be done for `HttpStartStop` events because they are not aggregated, they simply report each HTTP request/response (and using 2 different envelopes, one for the client duration and another for the server). This means that I need to aggregate/summarize the `HttpStartStop` events at the exporter, and this is something that it's out of the scope of my original idea.

Besides the above comments, I understand your problem and agree that it can be really useful to export those metrics. I have been doing some experiments this weekend, and I have implemented a basic prototype that summarizes those events only for application related HTTP requests.

This prototype has also some challenges:

* In order to aggregate/summarize the events, I need to store them in memory, and on a highly loaded CF environment, the number of events that needs to be stored and/or aggregated might be quite high. I'm not quite sure how the prototype will behave on such environments, how much memory it will require and if it will be able to handle the firehose throttle.

* The way that the exporter emits those events is by summarizing them using [quantiles](https://en.wikipedia.org/wiki/Quantile) (`0.5`, `0.9` and `0.99`), and this present some challenges when you want to do aggregations. I'd love to have used `histograms` instead, but this requires configuring the right bucket sizes, and every app might have a different set of requirements, so this means that I need to make the bucket sizes configurable by app, and I believe this is too much complexity for this exporter. Please check the [Histograms and Summaries](https://prometheus.io/docs/practices/histograms/) section at the Prometheus documentation to see the challenges of those approaches.

You can check the [FAQ](https://github.com/cloudfoundry-community/firehose_exporter/blob/master/FAQ.md#httpstartstop-metrics) to see what metrics are reported now for `HttpStartStop` events. Please take a look and let me know what do you think. Also, please bear in mind this is the 1st prototype, I still consider it **experimental** and I may change it completely in the future or just discard it if it does not fulfill our requirements.

I've also started creating some dashboards based on your comments. Please check the [cf_apps_*.json](https://github.com/cloudfoundry-community/prometheus-boshrelease/tree/master/src/cloudfoundry_dashboards) files at the Prometheus BOSH release and let me know what do you think.

**Comment by gberche-orange** [comment]
Thanks a lot @frodenas for this great work! Some initial feedback just reading the code, I hope to provide more relevant feedback once we have actually installed and used the cf_apps_*.json dashboards.

> You can check the FAQ to see what metrics are reported now for HttpStartStop events. Please take a look and let me know what do you think

* I'm wondering whether the URI label should be kept as this seems a dimension with unbounded high cardinality that might use [lots of storage data](https://prometheus.io/docs/practices/naming/#labels)
* Similarly,  the ``instanceId`` dimension seems unbounded, whether the ``instanceIndex`` seems of much lower cardinality (possibly fitting within 8 or 16 bits unsigned integers)
* Related to the duration expressed in seconds, I understand their are computed as [float64](https://github.com/cloudfoundry-community/firehose_exporter/blob/d56f0f659e1c1907c9e3508ba4dd568750851772/utils/timestamp.go#L7-L9), and I guess prometheus is able to leverage float64 decimal precisions metrics without loosing nanoseconds resolutions.

> Metrics are cached (with a expirity defined at the doppler.metric-expiration command flag). The exporter emits a summary of the HttpStartStop requests not expired using quantiles (0.5, 0.9, 0.99).

How does the caching compares to a potential: ``the exporter reports metrics summary from sliding window. The sliding window's size ``doppler.metric-expiration`` seconds`` ?

> on a highly loaded CF environment, the number of events that needs to be stored and/or aggregated might be quite high. I'm not quite sure how the prototype will behave on such environments, how much memory it will require and if it will be able to handle the firehose throttle.

I agree there are probably too many returned metrics in the [current code-base](https://github.com/cloudfoundry-community/firehose_exporter/blob/d56f0f659e1c1907c9e3508ba4dd568750851772/collectors/http_start_stop_collector.go#L175-L200). If I understand correctly, for 1000 apps, with each 5 instances, and each 100 URIs, and 10 status codes, this ends up into 1000*5*10*10=500k * 5 quantile metrics emitted and stored in prometheus every N seconds. Removing the URI dimension will reduce part of it.

We might need to distinguish different types of use-cases:
a- drilldown from routing provided metrics to per app details
b- per app routing metrics (for supporting diagnostic of a specific app, including the autosleep use-case)
c- autosleep 

For a) The statusCode and method are probably not necessary. This ends up with 1000*5*5=25k quantile metrics emited regularly. Only top N application ids (say top 10 or top 100) might be sufficient to reduce to an acceptable 250-2,500 metrics, making it generally applicable.

For b) (i.e. per app metrics)
* it might make sense to support inclusion and exclusion patterns for applications (e.g. based on org names, such as "production" or "premium")

For c) (autosleep)
* for the specific case of autosleep, a metric ``http_start_stop_last_request_timestamp`` with single dimension/label ``application_id`` is useful. In our example with 1,000 active apps, this ends up with 1,000 metrics emitted regulary. If only 100 apps are active, and 9900 are stopped/sleeting, we end up with 100 metrics emitted regulary.

**Comment by mjseid** [comment]
Awesome work @frodenas.  I was thinking about how to get these metrics as well recently, since I think they would be very useful to both devs and operators.

As you mentioned because prometheus is a scrape model and the router metrics are just dumped as a log stream I was thinking of achieving this via a separate workflow:  namely using the firehose-influxdb nozzle to dump them to influx.  

The pro of that in my mind would be scalability and granularity of metrics where you aren't having to aggregate or summarize to fit everything in this exporter.  In that model if needed (we're getting close due to firehose throughput) you could scale up multiple nozzles all dumping to the central influx for persistence since the nozzles are just transforming the dataflow.  Not sure how that will work with multiple prometheus exporter nozzles in this project.  Also Grafana could still be used as the dashboard which is nice.

The con is obviously having multiple monitoring systems and not being able to utilize alertmanager for alerts.  Maybe you could have a prometheus exporter that reads these desired metrics from influx rather then directly from the firehose?  

I haven't had a chance to try out the httpstartstop improvements you've made here yet but looking forward to it and wanted to add some thoughts to the discussion.

**Comment by frodenas** [comment]
@gberche-orange @poblin-orange As discussed last Friday:

> I'm wondering whether the URI label should be kept as this seems a dimension with unbounded high cardinality that might use lots of storage data

Indeed, the `HttpStartStop` collector returns metrics with too many dimensions. I'm not especially concerned about the storage data, as I haven't seen a huge size increase since I implemented it (and remember that by default, metrics are store only 15 days, configurable by the `storage.local.retention` property). I'm more concerned about performance issues when querying the data. But I still consider this collector an experiment, and I don't want to limit right now what we may expose as metrics and labels. If later we feel that most of the labels are useless or even harmful, then we can easily drop them.

> Similarly, the instanceId dimension seems unbounded, whether the instanceIndex seems of much lower cardinality (possibly fitting within 8 or 16 bits unsigned integers)

During my experiments, the `instance index` is always `0` regardless of the number of instances and even when having different `instance id`. This is why I switched to `instance id` by default. I need to check this with the loggregator team.

> Related to the duration expressed in seconds, I understand their are computed as float64, and I guess prometheus is able to leverage float64 decimal precisions metrics without loosing nanoseconds resolutions.

Yes, you will NOT loose ns resolutions. There're plenty of grafana dashboards that show ns resolutions for metrics exposing seconds.

> How does the caching compares to a potential: the exporter reports metrics summary from sliding window. The sliding window's sizedoppler.metric-expirationseconds ?

You used a better wording than I :) I updated the FAQ to reflect this.

**Comment by frodenas** [comment]
@mjseid Thanks for your thoughts!

There're basically 3 reasons why I choose Prometheus over InfluxDB:

1. Prometheus has an already broad set of exporters. When monitoring a CF environment, Elastic Runtime is just one component, and I want to be able to monitor CF's backing storages (etcd, MySQL, Consul, Nats, ...) and even the services that I provide at the marketplace (MySQL, RabbitMQ, Redis, ...). With Prometheus, I was able to archive that without the need to create my own exporters.
2. I was also really interested in alerting without needing to look for another solution. When I started this project, Grafana didn't have an alerting system (it has been delivered some weeks ago, starting at v4.0.0), and Prometheus provided an HA solution out of the box with multiple configurable receivers.
3. Similar to 1), I started the [Prometheus BOSH release](https://github.com/cloudfoundry-community/prometheus-boshrelease) to monitor systems that are outside of the CF community. Later, when playing with it, I realized that creating a firehose exporter was an easy task, so consider this exporter as collateral to my initial goals :)

So far, Prometheus has worked quite well for my goals. Things started to be more challenging when I added the `HttpStartStop` collector. Basically, because Prometheus is NOT a time series database, and `HttpStartStop` metrics are returned as a set of events. I'm not against the idea of using another solution for those events if that makes sense, and InfluxDB may be a nicer solution.

w/r/t having multiple nozzles, I'm currently testing this approach (1 firehose exporter per AZ, 1 prometheus server also per AZ, and then a global prometheus server that federates both AZs, something similar to this [diagram](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/docs/Deployment%20Topology.svg)). It has some challenges, basically because the fact that the loggregator evenly distribute the metrics between the nozzles doesn't help when you need to do aggregation at the nozzle level, but I believe this can be easily solved at the grafana level. But again, I just started testing this.

**Comment by frodenas** [comment]
@gberche-orange I've running the `HttpStartStop` collector for a while on a medium CF deployment and haven't seen any issue with Prometheus. Although this, I don't feel that having so much cardinality for the `uri` label is going to help on a high loaded environment. So I've updated the collector to export only the `schema` and `host` labels.

I'm closing this issue, but feel free to reopen it if you have any concerns.
